export const testIconNamesExt = [
  'add.svg',
  'calendar.svg',
  'chevron-down.svg',
  'chevron-left.svg',
  'chevron-right.svg',
  'chevron-up.svg',
  'clock.svg',
  'close.svg',
  'commenting.svg',
  'comments.svg',
  'ellipsis-vertical.svg',
  'ellipsis.svg',
  'gear.svg',
  'home.svg',
  'mail.svg',
  'menu.svg',
  'people.svg',
  'person.svg',
  'search.svg',
  'shopping-cart.svg',
  'star.svg',
  'trash.svg',
]

export const testIconsNames = testIconNamesExt.map((name) => name.match(/(.*)\.svg/)[1])
