name: "PNPM Install & Cache"

description: "Install and cache dependencies using pnpm"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7.25.0
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
      shell: bash