name: publish

on:
  push:
    branches:
      - 'releases/[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/pnpm-install
      - name: Run Tests
        run: npm run test
      - uses: ./.github/write-version

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/pnpm-install
      - run: npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_REPO_ADMIN }}
      - uses: ./.github/read-version
      - uses: ./.github/pnpm-install
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist
      - name: Bump dist version
        working-directory: ./dist
        run: npm --no-git-tag-version version ${{ env.pkg_version }}
      - name: Publish to NPM
        working-directory: ./dist
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Bump repo version
        run: npm version ${{ env.pkg_version }}
      - name: Merge/Tag
        run: |
          git fetch origin
          git pull origin
          git commit -a
          git checkout main
          git pull origin
          git merge ${{ github.ref_name }}
          git tag -a v${{ env.pkg_version }} -m "Release v${{ env.pkg_version }}"
          git push origin main --tags
      - name: Publish Release
        run: |
          tar -cvzf v$(echo ${{ github.ref_name }} | cut -d / -f 2-).tgz /dist
          gh release create v$(echo ${{ github.ref_name }} | cut -d / -f 2-) v$(echo ${{ github.ref_name }} | cut -d / -f 2-).tgz --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_REPO_ADMIN }}

          
          
